### ISSUE TITLE
Feature: Print timestamps using Discord timestamps

### ISSUE THREAD

**Issue by tzakrajs** [redactedaccount/PashaBot#2]
Instead of: 1. A: The Matrix (Added by mantisek on 2024-03-10 04:50:37)

Why not: 1. A: The Matrix (Added by mantisek <t:1710114600:R> on <t:1710114600:f>)

Which renders: 1. A: The Matrix (Added by mantisek 4 days ago on March 10, 2024 at 4:50 PM)

**Comment by redactedaccount** [comment]
Oooh, did not know this. Great suggestion.

**Comment by redactedaccount** [comment]
https://github.com/redactedaccount/PashaBot/commit/ff981371208eb95ef91d7f320d08da146c6085b1

Feature implemented, also made the output an embed.  Although this presents a new problem:  Output may quickly exceed Discord's character limit. 

New issue created:  https://github.com/redactedaccount/PashaBot/issues/6
