### ISSUE TITLE
Previous Processed Movies

### ISSUE THREAD

**Issue by sagostin** [redactedaccount/PashaBot#9]
User Story:
Users must be able to view previously played movies, and it must not play movies based on previously played, unless X amount of time has passed.

Discussion:
What amount of time must have passed to not/allow previously played movies

**Comment by redactedaccount** [comment]
This is a good question.  I was planning to make an 'archived' bool column.

Would you say at this point it's probably better to just create the option to accept a randomly chosen movie, and archive it, and think about what sort of process we want for re-watching movies much later down the line? 

It'll be one movie per list per week, and we have about 15 movies in both lists, so if we didn't add any more movies, we'd have almost 5 months to come up with something.

**Comment by redactedaccount** [comment]
[43d044d](https://github.com/redactedaccount/PashaBot/commit/43d044d13eaabb8956306f108544122388705f82)

Added command to archive movies, and list archived movies.
